
export { default as Navbar } from './Navbar';
export { default as Services } from './Services';
export { default as Welcome } from './Welcome';
export { default as Footer } from './Footer';
export { default as About } from './About';
export { default as Contact } from './Contact';
export { default as login } from '../pages/login'
export { default as connect } from '../pages/connect'
export { default as Sidebar } from './Sidebar'
export { default as Outlet } from './Outlet'
export { default as Down } from './Down'
export { default as Header } from './Header'
export { default as Mid } from './Mid'
export { default as Footer2 } from './Footer2'
export { default as Middle } from './Middle'
export { default as Forms } from './Forms'
export { default as SidebarAccount } from './Sidebaraccount'
export { default as SidebarData } from './Sidebardata'
export { default as Data } from './Data'
export { default as IndividualLogin } from '../pages/IndividualLogin'
export { default as BusinessLogin } from '../pages/BusinessLogin'
export { default as InstitutionLogin } from '../pages/InstitutionLogin'